application: ex-track
version: 1
runtime: java
threadsafe: true

context_params:
  contextConfigLocation: classpath:service-context.xml classpath:persistence-context.xml
  
listeners:
  - org.springframework.web.context.ContextLoaderListener

static_files:
  - include: resources/**
  
resource_files:
  - exclude: resources/**
  
handlers:
  - url: /
    servlet: org.springframework.web.servlet.DispatcherServlet
    init_params:
      contextConfigLocation: classpath:application-context.xml
    
inbound_services:
  - warmup
  
sessions_enabled: true