application: ex-track
version: 1
runtime: java
threadsafe: true

context_params:
  contextConfigLocation: classpath:service-context.xml classpath:persistence-context.xml classpath:security-context.xml
  
listeners:
  - org.springframework.web.context.ContextLoaderListener

static_files:
  - include: /resources/**
  - include: /favicon.ico
  
resource_files:
  - exclude: /resources/**
  - exclude: /favicon.ico
  
handlers:
  - url: /
    servlet: org.springframework.web.servlet.DispatcherServlet
    init_params:
      contextConfigLocation: classpath:application-context.xml
  - url: /*
    name: springSecurityFilterChain
    filter: org.springframework.web.filter.DelegatingFilterProxy
    
inbound_services:
  - warmup
  
sessions_enabled: true